# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 859e5ec4fada18f314a919fb3b7a3f7df8430c79351cb7dafcc70e754a2cc357c78126c252d045e8386a8e27c6ae9e10837d95593165a6802a11f4fb4acc3f68

test:
  secret_key_base: db438cd0a315b277cd33a2785cb04aa6b48f458c98497282ba59521fb9a7ad9ccba98fdbeb480804a997a720f621530b46c231153550a26d6e577d00cd6b1eab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
